### ISSUE TITLE
npm install interpo FAILS

### ISSUE THREAD

**Issue by samaraiza** [WhoopInc/interpo#2]
I attempted the following:
1. brew install gcc (a 30 min job, btw)
2. brew link --force gcc
3. brew unlink gcc && link gcc (as recommended in terminal)
4. brew link --force gcc
5. npm install interpo

samaraiza$ npm install interpo

> interpo@1.0.1 install /project/node_modules/interpo
> node-gyp rebuild

  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_0 Release/obj.target/slatec/geni/dchfev.o
  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_1 Release/obj.target/slatec/geni/dpchfe.o
  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_2 Release/obj.target/slatec/geni/dpchim.o
  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_3 Release/obj.target/slatec/geni/dpchst.o
  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_4 Release/obj.target/slatec/geni/fdump.o
  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_5 Release/obj.target/slatec/geni/i1mach.o
  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_6 Release/obj.target/slatec/geni/j4save.o
  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_7 Release/obj.target/slatec/geni/xercnt.o
  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_8 Release/obj.target/slatec/geni/xerhlt.o
  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_9 Release/obj.target/slatec/geni/xermsg.o
  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_10 Release/obj.target/slatec/geni/xerprn.o
  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_11 Release/obj.target/slatec/geni/xersve.o
  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_12 Release/obj.target/slatec/geni/xgetua.o
  RULE deps_slatec_slatec_gyp_slatec_target_build_fortran_13 Release/obj.target/slatec/geni/xsetf.o
  LIBTOOL-STATIC Release/slatec.a
  CXX(target) Release/obj.target/interpo/src/interpo.o
In file included from ../src/interpo.cc:1:
In file included from /Users/samaraiza/.node-gyp/8.1.4/include/node/node.h:63:
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:316:16: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using Handle = Local<T>;
               ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:333:33: error: use of undeclared identifier 'nullptr'
  V8_INLINE MaybeLocal() : val_(nullptr) {}
                                ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:340:51: error: use of undeclared identifier 'nullptr'
  V8_INLINE bool IsEmpty() const { return val_ == nullptr; }
                                                  ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:344:29: error: use of undeclared identifier 'nullptr'
    out->val_ = IsEmpty() ? nullptr : this->val_;
                            ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:364:30: error: use of undeclared identifier 'nullptr'
  V8_INLINE Eternal() : val_(nullptr) {}
                             ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:366:63: error: use of undeclared identifier 'nullptr'
  V8_INLINE Eternal(Isolate* isolate, Local<S> handle) : val_(nullptr) {
                                                              ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:371:51: error: use of undeclared identifier 'nullptr'
  V8_INLINE bool IsEmpty() const { return val_ == nullptr; }
                                                  ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:411:25: error: use of undeclared identifier 'nullptr'
    return callback_ != nullptr;
                        ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:435:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class WeakCallbackType { kParameter, kInternalFields, kFinalizer };
     ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:575:49: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  PersistentBase(const PersistentBase& other) = delete;  // NOLINT
                                                ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:576:43: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  void operator=(const PersistentBase&) = delete;
                                          ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:769:26: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
  V8_INLINE Global(Global&& other) : PersistentBase<T>(other.val_) {  // NOLINT
                         ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:777:40: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
  V8_INLINE Global& operator=(Global<S>&& rhs) {  // NOLINT
                                       ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:796:27: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  Global(const Global&) = delete;
                          ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:797:35: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  void operator=(const Global&) = delete;
                                  ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:745:42: error: use of undeclared identifier 'nullptr'
  V8_INLINE Global() : PersistentBase<T>(nullptr) {}
                                         ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:770:18: error: use of undeclared identifier 'nullptr'
    other.val_ = nullptr;
                 ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:782:18: error: use of undeclared identifier 'nullptr'
      rhs.val_ = nullptr;
                 ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:789:44: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
  Global Pass() { return static_cast<Global&&>(*this); }  // NOLINT
                                           ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:808:26: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using UniquePersistent = Global<T>;
                         ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:840:37: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  HandleScope(const HandleScope&) = delete;
                                    ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:841:40: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  void operator=(const HandleScope&) = delete;
                                       ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:892:55: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  EscapableHandleScope(const EscapableHandleScope&) = delete;
                                                      ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:893:49: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  void operator=(const EscapableHandleScope&) = delete;
                                                ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:907:45: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  SealHandleScope(const SealHandleScope&) = delete;
                                            ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:908:44: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  void operator=(const SealHandleScope&) = delete;
                                           ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1089:52: error: use of undeclared identifier 'nullptr'
                            ScriptOrigin* origin = nullptr));
                                                   ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1092:30: error: use of undeclared identifier 'nullptr'
      ScriptOrigin* origin = nullptr);
                             ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1152:37: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
    CachedData(const CachedData&) = delete;
                                    ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1153:48: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
    CachedData& operator=(const CachedData&) = delete;
                                               ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1176:29: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
    Source(const Source&) = delete;
                            ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1177:40: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
    Source& operator=(const Source&) = delete;
                                       ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1264:45: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
    StreamedSource(const StreamedSource&) = delete;
                                            ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1265:56: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
    StreamedSource& operator=(const StreamedSource&) = delete;
                                                       ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1627:24: error: use of undeclared identifier 'nullptr'
  RegisterState() : pc(nullptr), sp(nullptr), fp(nullptr) {}
                       ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1627:37: error: use of undeclared identifier 'nullptr'
  RegisterState() : pc(nullptr), sp(nullptr), fp(nullptr) {}
                                    ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1627:50: error: use of undeclared identifier 'nullptr'
  RegisterState() : pc(nullptr), sp(nullptr), fp(nullptr) {}
                                                 ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1799:45: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  ValueSerializer(const ValueSerializer&) = delete;
                                            ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1800:44: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  void operator=(const ValueSerializer&) = delete;
                                           ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1893:49: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  ValueDeserializer(const ValueDeserializer&) = delete;
                                                ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:1894:46: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  void operator=(const ValueDeserializer&) = delete;
                                             ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:2308:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class NewStringType { kNormal, kInternalized };
     ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:2432:69: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
    ExternalStringResourceBase(const ExternalStringResourceBase&) = delete;
                                                                    ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:2433:57: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
    void operator=(const ExternalStringResourceBase&) = delete;
                                                        ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:2519:42: warning: use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
    kNormalString = static_cast<int>(v8::NewStringType::kNormal),
                                         ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:2520:48: warning: use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
    kInternalizedString = static_cast<int>(v8::NewStringType::kInternalized)
                                               ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:2640:35: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
    Utf8Value(const Utf8Value&) = delete;
                                  ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:2641:40: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
    void operator=(const Utf8Value&) = delete;
                                       ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:2663:27: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
    Value(const Value&) = delete;
                          ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:2664:36: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
    void operator=(const Value&) = delete;
                                   ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:2873:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class KeyCollectionMode { kOwnOnly, kIncludePrototypes };
     ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:2879:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class IndexFilter { kIncludeIndices, kSkipIndices };
     ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:2884:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class IntegrityLevel { kFrozen, kSealed };
     ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:3649:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class ConstructorBehavior { kThrow, kAllow };
     ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:3663:38: warning: use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
      ConstructorBehavior behavior = ConstructorBehavior::kAllow);
                                     ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:3677:36: error: use of undeclared identifier 'nullptr'
    return NewInstance(context, 0, nullptr);
                                   ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:3904:51: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  PropertyDescriptor(const PropertyDescriptor&) = delete;
                                                  ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:3905:47: warning: deleted function definitions are a C++11 extension
      [-Wc++11-extensions]
  void operator=(const PropertyDescriptor&) = delete;
                                              ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:3938:26: error: no member named 'unique_ptr' in namespace 'std'
  typedef std::pair<std::unique_ptr<const uint8_t[]>, size_t> SerializedModule;
                    ~~~~~^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:3938:37: error: expected expression
  typedef std::pair<std::unique_ptr<const uint8_t[]>, size_t> SerializedModule;
                                    ^
/Users/samaraiza/.node-gyp/8.1.4/include/node/v8.h:3938:53: error: expected member name or ';' after declaration specifiers
  typedef std::pair<std::unique_ptr<const uint8_t[]>, size_t> SerializedModule;
  ~~~~~~~                                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
42 warnings and 20 errors generated.
make: *** [Release/obj.target/interpo/src/interpo.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.1.4/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/samaraiza/OneDrive/projects/TRIP/obscure-shore-36175/node_modules/interpo
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! interpo@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the interpo@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samaraiza/.npm/_logs/2017-09-13T16_21_50_485Z-debug.log

**Comment by benesch** [comment]
Seems like node-gyp isn't using with the freshly installed g++. Assuming you're installing GCC 7 (i.e., what `brew install gcc` is currently shipping), try:

```
CC=gcc-7 CXX=g++-7 npm install interpo
```

**Comment by benesch** [comment]
Closing due to inactivity.
